###user api req

post http://localhost:4000/user-api/register
Content-Type: application/json

{
    "userType":"user",
    "username":"aash1",
    "password":"aash",
    "email":"aash@gmail.com"
}

###
post http://localhost:4000/user-api/login
Content-Type: application/json

{
    "userType":"user",
    "username":"aash",
    "password":"aash"
}


###
post http://localhost:4000/user-api/comment
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhc2giLCJpYXQiOjE3MDk4NDQ3Nzd9.eJVQyVsAJXOJyQ49EWjrP9_4pQ6cqs0YJbNmVJY3sx0
Content-Type: application/json

{
  "articleId":"",
  "username":"aashritha",
  "comment":"hello"
}

###reading articles of all users

get http://localhost:4000/user-api/articles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhc2giLCJpYXQiOjE3MDk4NDQ3Nzd9.eJVQyVsAJXOJyQ49EWjrP9_4pQ6cqs0YJbNmVJY3sx0

###
post http://localhost:4000/author-api/register
Content-Type: application/json

{
    "userType":"author",
    "username":"arjun",
    "password":"arjun",
    "email":"arjun@gmail.com"
}

###

post http://localhost:4000/author-api/login
Content-Type: application/json

{
    "userType":"author",
    "username":"arjun",
    "password":"arjun"
}
###

get http://localhost:4000/author-api/articles/arjun
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzA5ODQyNzEwLCJleHAiOjE3MDk5MjkxMTB9.jLhlcJ9p-9g2ZWBjwK1qdRzdkv-BrZCqnfo4F5ZUE_s

###
post http://localhost:4000/author-api/article
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzA5ODQyNzEwLCJleHAiOjE3MDk5MjkxMTB9.jLhlcJ9p-9g2ZWBjwK1qdRzdkv-BrZCqnfo4F5ZUE_s
Content-Type: application/json

{
    "articleId":"{{$timestamp}}",
   "title":"Fundamentals of JavaScript",
   "category":"programming",
   "content":"JavaScript is a high-level programming language that follows the ECMAScript standard. It was originally designed as a scripting language for websites but became widely adopted as a general-purpose programming language, and is currently the most popular programming language in use.[1] JavaScript is usually found running in a web browser as interactive or automated content, ranging from popup messages and live clocks to large web applications. JavaScript is also commonly used in server-side programming through platforms like Node.js,[2] or embedded in non-JavaScript applications where the base programming language lacks the high-level functionality that JavaScript offers.",
   "dateOfCreation":"{{$datetime iso8601}}",
   "dateOfModification":"{{$datetime iso8601}}",
   "username":"arjun",
   "comments": [ ],
   "status":true
}

###
put http://localhost:4000/author-api/article
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzA5ODQyNzEwLCJleHAiOjE3MDk5MjkxMTB9.jLhlcJ9p-9g2ZWBjwK1qdRzdkv-BrZCqnfo4F5ZUE_s
Content-Type: application/json

{
   "articleId":"1709843110",
   "title":"Fundamentals of JavaScript",
   "category":"programming",
   "content":"JavaScript is a high-level programming language that follows the ECMAScript standard. It was originally designed as a scripting language for websites but became widely adopted as a general-purpose programming language, and is currently the most popular programming language in use.[1] JavaScript is usually found running in a web browser as interactive or automated content, ranging from popup messages and live clocks to large web applications. JavaScript is also commonly used in server-side programming through platforms",
   "dateOfCreation":"2024-02-26T13:56:22.487Z",
   "dateOfModification":"{{$datetime iso8601}}",
   "username":"arjun",
   "comments": [ ],
   "status":true
   
}
### soft delete an article by article id
put http://localhost:4000/author-api/article/1709843110
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFyanVuIiwiaWF0IjoxNzA5ODQyNzEwLCJleHAiOjE3MDk5MjkxMTB9.jLhlcJ9p-9g2ZWBjwK1qdRzdkv-BrZCqnfo4F5ZUE_s
Content-Type: application/json

{
   "articleId":"1709843110",
   "title":"Fundamentals of JavaScript",
   "category":"programming",
   "content":"JavaScript is a high-level programming language that follows the ECMAScript standard. It was originally designed as a scripting language for websites but became widely adopted as a general-purpose programming language, and is currently the most popular programming language in use.[1] JavaScript is usually found running in a web browser as interactive or automated content, ranging from popup messages and live clocks to large web applications. JavaScript is also commonly used in server-side programming through platforms",
   "dateOfCreation":"2024-02-26T13:56:22.487Z",
   "dateOfModification":"{{$datetime iso8601}}",
   "username":"arjun",
   "comments": [ ],
   "status":true
   
}
###
###
post http://localhost:4000/user-api/comment/1709843110
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhc2giLCJpYXQiOjE3MDk4ODk1OTZ9.OX6Wz9sT-Lo1EImvauiQLCSenznrsXFgandRx22Nf7s
Content-Type: application/json

{
    "articleId":"1709843110",
    "username":"arjun",
    "comment":"hi"
}